- commands/announceBot.py
Changed #bot-help -> <#342060723721207810>
And changed #bug-bounties -> <#274590523719811074> so it mentions instead of sending plain text
> Channel mentions are cool

- .gitignore
- commands/announce.py
- commands/config.py
cleaned up the lockdown command so it no longer has duplicate code
fix reaction perms getting reset upon locking
add unlock command (cleans up lock messages)
also includes message fix from #5
> cleanup of lockdown and add unlock command

- commands/announce.py
as requested, takes a mention or ID as parameter
> employee command

- commands/config.py
- commands/experience.py
- example.config.yaml
- requirements.txt
adds an XP plugin for bug hunters.
> add experience plugin

- .gitignore
- commands/announce.py
- commands/events.py
- commands/experience.py
- commands/pager.py
- util/Pages.py
- util/Pie.py
- util/Utils.py
adds a pie char with approved/denied/submitted to `+event stats`
adds `+event pie <stat>` command to make even more pie charts
valid stats:
- participants
- platforms
- lists
- vs
- the id (or @mention) of a person who participated in the event
pie charts are made with the matplotlib so that module will have to be installed using pip
> event stats

- commands/experience.py
Added a '+shop' alias to the store command. I also changed "shop" to "store" in the embed.
> Minor changes to the +store command

- .gitignore
- commands/experience.py
made an error log, so make sure to set an error log channel in the config.
(also i might have broken a few things)
> updates and bug fixes to xp system

- commands/announce.py
Adds a command to change the server verification level with an optional reason. Level values range from `none` to `extreme` ([full list](https://github.com/b1naryth1ef/disco/blob/master/disco/types/guild.py#L21))
> Add change verification level command

- commands/config.py
- commands/experience.py
- commands/guide.py
- commands/pager.py
> add guides and make store have pages

- commands/guide.py
- util/GlobalHandlers.py
fixes a bug where people who aren't bug hunters can't use the guides.
> [guide] fix permission bug

- commands/announce.py
Minor updates to logging (command usage/exceptions) requested in #27 that I missed
> Fixed logging for verification command

- commands/config.py
- commands/experience.py
- commands/mentor.py
- example.config.yaml
> Adds mentor plugin

- commands/notify.py
Has a more generalised pattern but should no longer bork on spaces/unicode...etc in usernames
> Fix regex in notify plugin

- commands/notify.py
- Trello links should no longer be converted to lowercase
- Catches exceptions when deleting invoke messages in the reporting channels/queue in case Bug Bot caught them first
- Fixes an error if 'none' is used as a scope keyword
> Fix notify issues

- commands/events.py
- commands/experience.py
- commands/guide.py
- util/Pages.py
minor changes that don't need deploying soon, just to make the paginator work without an explicit command being executed for @brxxn 's guide stuff
> tweak paginator to work without a event

- commands/config.py
Just fixed up a minor spelling error that was found by Sajuuk.
> Minor spelling fix.

- commands/announce.py
- commands/events.py
- commands/experience.py
- commands/guide.py
- commands/interactions.py
- commands/notify.py
- commands/pager.py
- commands/reload.py
also fix other plugins load and unload calls as they where not behaving, some where not needed, one unload was even calling the load function
while this reloads the plugins and configs, it doesn't load the new code if the file was changed on disk, tried that but didn't work for some reason, will take another crack at that later
it's also in a seperate plugin as disco kills everything that is running when you unload a plugin, so it doesn't reload the reloading plugin itself
> add reload plugin

- commands/mentor.py
I don't really know disco.py very well, so feel free to correct any mistake I did in this code. It adds a message body immediately before the embed so that the mention renders and for any user that might be disabling link previews (but then, why would you be? :P)
> added msg body

- commands/reload.py
as requested, since it runs as a service this will allow the bot to shut down, and the service will just start again automatically
> restart command

- commands/announce.py
> Added slowmode

- README.md
Added information about the slowmode command also an example usage.
> Added slowmode info in readme

- commands/__init__.py
- commands/client.py
- commands/reactions.py
- commands/trello.py
- example.config.yaml
It might be good to try out on a test DB before prod, tho i'm pretty sure it all works fine.
I feel like there's a better way to check if ppl repro'd or not.
> Moving EvilPebbles stuff to EvilDabbit, and more

- commands/config.py
- commands/experience.py
also tweaked givexp logging a bit to match
> add reward command
